// Generated by IcedCoffeeScript 1.4.0b
var Model;

Model = (function() {

  function Model(name) {
    this.tables = [];
    this.relations = [];
  }

  Model.prototype.addTable = function(canvas, x, y) {
    return new Table(canvas, x, y, 100, 60);
  };

  Model.prototype.addRelation = function() {};

  return Model;

})();

if (typeof window === "undefined" || window === null) module.exports = Model;
