`/** @jsx React.DOM */`

goog.provide 'dm.ui.Table'
goog.provide 'dm.ui.Table.EventType'
goog.provide 'dm.ui.tmpls'

goog.require 'goog.dom'
goog.require 'goog.dom.query'
goog.require 'goog.style'
goog.require 'goog.math.Coordinate'
goog.require 'goog.math.Size'
goog.require 'goog.ui.Component'
goog.require 'goog.events'
goog.require 'goog.fx.Dragger'
goog.require 'dm.ui.utils'

class dm.ui.Table extends goog.ui.Component
	@EventType =
		CATCH: goog.events.getUniqueId 'table-catch'	
		MOVE: goog.events.getUniqueId 'table-move'
		MOVED: goog.events.getUniqueId 'table-move-end'

	###*
  * @param {dm.model.Table} tableModel
  * @param {number=} x Coordinate on x axis
  * @param {number=} y Coordinate on y axis
  * @param {string=} id Id of component, if not passed then it's autogenerated
  * @constructor
  * @extends {goog.ui.Component}
	###
	constructor: (tableModel, x = 0, y = 0, id) ->
		super()

		#@size_ = new goog.math.Size w, h
		###*
    * @type {goog.math.Coordinate}
		###
		@position_ = new goog.math.Coordinate x, y

		###*
    * @type {Element}
		###
		@head_ = null
		
		###*
    * @type {Element}
		###
		@body_ = null

		###*
    * @type {goog.fx.Dragger}
		###
		@dragger = null

		@setModel tableModel

		@setId id ? @getId()

	###*
  * @override
	###
	createDom: =>
		model = @getModel()
		element = dm.ui.utils.createElementFromReactComponent dm.ui.tmpls.Table(
			{id: @getId(), name: model.getName(), columns: model.getColumns()}
		)
		
		@head_ = goog.dom.getElementByClass 'head', element
		@body_ = goog.dom.getElementByClass 'body', element

		@setElementInternal element

	###*
  * @override
	###
	enterDocument: ->
		super()

		element = @getElement()
		goog.style.setPosition element, @position_.x, @position_.y
		
		@dragger = new goog.fx.Dragger element, element, @getDragLimits()


		goog.events.listen @dragger, 'start', @dragStartEnd
		
		goog.events.listen @dragger, 'drag', (ev) => 
			@setPosition ev.left, ev.top
			@dispatchEvent dm.ui.Table.EventType.MOVE
		
		goog.events.listen @dragger, 'end', @dragStartEnd
		goog.events.listen @dragger, 'end', => 
			@dispatchEvent dm.ui.Table.EventType.MOVED

		canvas = dm.ui.Canvas.getInstance()
		goog.events.listen canvas, dm.ui.Canvas.EventType.RESIZED, =>
			@dragger.setLimits @getDragLimits()

		return

	###*
  * @this {goog.fx.Dragger}
	###	
	dragStartEnd: (e) ->
		#@target.style.zIndex = if e.type is 'start' then 99 else 1
		@target.style.cursor = if e.type is 'start' then 'move' else 'default'
		goog.style.setOpacity @target, if e.type is 'start' then 0.7 else 1

	###*
  * @override
	###
	setModel: (model) ->
		model = (`/** @type {dm.model.Table} */`) model
		super model

		goog.events.listen model, 'name-change', (ev) => 
			@setName ev.target.getName()
		
		goog.events.listen model, 'column-change', (ev) =>
			@updateColumn ev.column.id, ev.column.data
		
		goog.events.listen model, 'column-add', (ev) =>
			@addColumn ev.column.id, ev.column.data
			@dragger.setLimits @getDragLimits()
		
		goog.events.listen model, 'column-delete', (ev) =>
			@removeColumn ev.column.id
			@dragger.setLimits @getDragLimits()

		return

	###*
  * @param {number} x
  * @param {number} y
	###
	setPosition: (x, y) =>
		# table's position coordinates and size dimensions
		@position_.x = x
		@position_.y = y

		if @isInDocument()
			goog.style.setPosition @getElement(), @position_.x, @position_.y

  ###*
  * @return {goog.math.Coordinate}
  ###
	getPosition: ->
		@position_

	###*
  * @return {goog.math.Rect}
	###
	getDragLimits: ->
		csz = dm.ui.Canvas.getInstance().getSize()
		tsz = @getSize() 
		
		new goog.math.Rect 0, 0, csz.width - tsz.width - 4, csz.height - tsz.height - 4

	###*
  * @return {goog.math.Size} table dimensions
	###
	getSize: ->
		goog.style.getSize @getElement()

	###*
  * @param {string} name Name of table
	###
	setName: (name = '') ->		
		goog.dom.setTextContent @head_, name		

	###*
  * @param {string} id
  * @param {dm.model.TableColumn} column
	###
	addColumn: (id, column) ->
		@body_.innerHTML += React.renderComponentToStaticMarkup(
			dm.ui.tmpls.Column {id: id, data: column}
		)

	###*
	* @param {string} id
	* @param {dm.model.TableColumn} column
	###
	updateColumn: (id, column) ->
		oldColumn = goog.dom.query("[name='#{id}']", @body_)[0]
		newColumn = dm.ui.utils.createElementFromReactComponent(
			dm.ui.tmpls.Column {id: id, data: column}
		)

		goog.dom.replaceNode newColumn, oldColumn

	###*
  * @param {string} id
	###
	removeColumn: (id) ->
		column = goog.dom.query("[name=#{id}]", @body_)[0]
		goog.dom.removeNode column

# Table templates
dm.ui.tmpls.Table = React.createClass
	render: ->
		{TableColumns} = dm.ui.tmpls

		`(
		<div className="table" id={this.props.id}>
			<span className="head">{this.props.name}</span>
			<TableColumns cols={this.props.columns} />
		</div>
		)`

dm.ui.tmpls.TableColumns = React.createClass
	render: ->
		{Column} = dm.ui.tmpls
		columns = []
		
		goog.object.forEach @props.cols, (data, id) ->
			columns.push `( <Column id={id} data={data} key={id} /> )`

		`( <div className="body">{columns}</div> )`

dm.ui.tmpls.Column = React.createClass
	createIndex: (index) ->
		`( <span className="idx" key={index} >{index}</span> )`


	render: ->
		{id, data} = @props
		indexes = goog.array.map (data.indexes ? []), @createIndex

		`(
		<div className="column" name={id}>
			<span>{data.name}</span>
			{indexes}				
		</div>
		)`

