// Generated by IcedCoffeeScript 1.4.0b
(function() {
  var app, dbDefs, express, fs, port;

  fs = require('fs');

  express = require('express.io');

  app = express();

  app.http().io();

  dbDefs = [];

  app.configure(function() {
    app.set('view engine', 'jade');
    app.set('views', __dirname + '/views');
    return app.use(express["static"](__dirname + '/public'));
  });

  app.get('/', function(req, res) {
    if (!dbDefs.length) {
      return fs.readdir('defs', function(err, files) {
        if (err) {
          return console.log('Error at reading defs dir!');
        } else {
          dbDefs = files;
          return res.render('intro', {
            dbs: files
          });
        }
      });
    } else {
      return res.render('intro', {
        dbs: dbDefs
      });
    }
  });

  app.get('/modeler', function(req, res) {
    return res.render('main');
  });

  port = 7076;

  app.listen(port, function() {
    return console.log('Listening on port ' + port);
  });

}).call(this);
