// Generated by IcedCoffeeScript 1.4.0b
var Server, app, express, port, routes, stylus;

express = require('express.io');

stylus = require('stylus');

routes = require('./src/routes');

global.Server = Server = {};

Server.app = app = express();

Server.databases = {};

Server.databases.dbs = {};

Server.databases.list = [];

Server.databases.selected = null;

app.http().io();

app.configure(function() {
  app.set('view engine', 'jade');
  app.set('views', __dirname + '/views');
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(stylus.middleware({
    src: __dirname + '/public'
  }));
  app.use(express["static"](__dirname + '/public'));
  app.use(app.router);
  return app.use(express.errorHandler());
});

app.get('/', routes.intro);

app.post('/modeler', routes.app);

app.get('/modeler', routes.app);

port = 7076;

app.listen(port, function() {
  return console.log('Listening on port ' + port);
});
