// Generated by IcedCoffeeScript 1.4.0b
var Relation;

Relation = (function() {

  Relation.prototype.startTab = null;

  Relation.prototype.endTab = null;

  function Relation() {}

  return Relation;

})();
