// Generated by IcedCoffeeScript 1.4.0b
var fs, routes;

fs = require('fs');

routes = {
  intro: function(req, res) {
    if (!Server.databases.list.length) {
      return fs.readdir('defs', function(err, files) {
        if (err) {
          return console.log('Error at reading defs dir!');
        } else {
          Server.databases.list = files;
          return res.render('intro', {
            dbs: files
          });
        }
      });
    } else {
      return res.render('intro', {
        dbs: Server.databases.list
      });
    }
  },
  app: function(req, res) {
    var options;
    if (!Server.databases.selected) {
      if (req.method === 'POST') {
        if (!req.body.dbs) {
          res.redirect('/');
          return;
        } else if (!Server.databases.dbs[req.body.dbs]) {
          Server.databases.selected = req.body.dbs;
          Server.databases.dbs[req.body.dbs] = {
            types: ['char', 'int', 'double']
          };
        }
      }
      if (req.method === 'GET') {
        res.redirect('/');
        return;
      }
    }
    options = {
      title: Server.databases.selected,
      types: Server.databases.dbs[Server.databases.selected].types
    };
    return res.render('main', options);
  }
};

module.exports = routes;
