// Generated by IcedCoffeeScript 1.4.0b
(function() {
  var fs, routes;

  fs = require('fs');

  routes = {
    intro: function(req, res) {
      if (!Server.databases.list.length) {
        return fs.readdir('defs', function(err, files) {
          if (err) {
            return console.log('Error at reading defs dir!');
          } else {
            Server.databases.list = files;
            return res.render('intro', {
              dbs: files
            });
          }
        });
      } else {
        return res.render('intro', {
          dbs: Server.databases.list
        });
      }
    },
    app: function(req, res) {
      return res.render('main');
    }
  };

  module.exports = routes;

}).call(this);
